[pytest]
testpaths = tests
addopts =
    -v
    --base-url https://automationexercise.com
    --browser chromium
    --screenshot only-on-failure
    --alluredir=allure-results
markers =
    smoke: швидкі критичні перевірки
    regression: повний набір тестів
    ui: тести інтерфейсу
    api: тести API
